### ISSUE TITLE
Support backlog & board view of JIRA next gen software projects

### ISSUE THREAD

**Issue by andreasknoepfle** [bitcrowd/tickety-tick#195]
JIRA has a new type of project which we do not yet support fully:

https://confluence.atlassian.com/jirasoftwarecloud/working-with-next-gen-software-projects-945104895.html

An example is e.g. our own bchp board: 
https://bitcrowd.atlassian.net/jira/software/projects/BCHP/boards/7

Both views currently make tickety-tick error out: 

![Screenshot 2019-11-28 at 18 47 10](https://user-images.githubusercontent.com/239398/69825431-9ca3a080-120f-11ea-9086-e7102f861c51.png)

**Comment by andreasknoepfle** [comment]
This is the errors that happen, just in case if it helps debugging this, which i don't believe :):

![Screenshot 2019-11-28 at 18 50 01](https://user-images.githubusercontent.com/239398/69825563-fe640a80-120f-11ea-8593-168b2ba69a8a.png)

**Comment by pmeinhardt** [comment]
Should be fixed on `master` now @andreasknoepfle. We just need a release, in case you have time (I'm quite busy with project work today) 😉

**Comment by andreasknoepfle** [comment]
Somehow it still does not work so much with next-gen projects. The errors above disappeared, but still no ticket is found with version `3.2.0`

**Comment by pmeinhardt** [comment]
Possibly related? https://github.com/bitcrowd/tickety-tick/issues/212#issuecomment-592428436

**Comment by klappradla** [comment]
Seems like we also have a problem with parsing the error we're getting for this scenario. That's what I get when debugging the extension:
```js
Error: "Cannot parse given Error object"
    parse error-stack-parser.js:35
    fromError stacktrace.js:106
    fromError stacktrace.js:105
    Ie error-details.jsx:18
    componentDidMount error-details.jsx:34
    Wo React
    unstable_runWithPriority scheduler.production.min.js:20
    React 9
    et render.jsx:31
    onload popup.js:39
error-details.jsx:36:30
    componentDidMount error-details.jsx:36
```
